name: dart_ffi_minimal
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

dev_dependencies:
  ffigen: any

environment:
  sdk: ">=3.0.0-12.0.dev <3.0.0"

ffigen:
  headers:
    entry-points:
      - native/native.h
  output: native/native.dart
  ffi-native:
